# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gelf < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.3/gelf_0.0.3_darwin_amd64.tar.gz"
      sha256 "7bab4fc15aab1c9a44caa1e04e9dfa88188ac0725e43ce99724de52d1dc0c9a9"

      def install
        bin.install "gelf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.3/gelf_0.0.3_darwin_arm64.tar.gz"
      sha256 "b0596fdc702d9bce3b04652f3a36750b70a3fbabbe67ee237640712d6cf2e82a"

      def install
        bin.install "gelf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.3/gelf_0.0.3_linux_amd64.tar.gz"
      sha256 "72fef23e29190f0c8eae9dc49efaf7918b6928e5cb9e9045cb0aac3a447022f4"
      def install
        bin.install "gelf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.3/gelf_0.0.3_linux_arm64.tar.gz"
      sha256 "91d6c2ef441a894798cbb19504556ada9fafb1f3ef0fa66c09e29c9f6a7f98a0"
      def install
        bin.install "gelf"
      end
    end
  end
end
