# This file was generated by GoReleaser. DO NOT EDIT.
cask "gelf" do
  desc "AI-powered Git commit message generator using Vertex AI (Gemini)"
  homepage "https://github.com/EkeMinusYou/gelf"
  version "0.0.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gelf"
  bash_completion "completions/gelf.bash"
  zsh_completion "completions/gelf.zsh"
  fish_completion "completions/gelf.fish"

  on_macos do
    on_intel do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.18/gelf_Darwin_x86_64.tar.gz"
      sha256 "2514fd3daaa12ba3b30eb9123b660ab29f4f60ef6a1c93c10bc656e270586ebd"
    end
    on_arm do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.18/gelf_Darwin_arm64.tar.gz"
      sha256 "8709959c317f25ff169aaa6ca40cf40e5c189598d30e4357ad7629f29fd07c9b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.18/gelf_Linux_x86_64.tar.gz"
      sha256 "26380d586f553db7ea032a80fb523b0a012c44a9d3ac37323af35e901cb08528"
    end
    on_arm do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.18/gelf_Linux_arm64.tar.gz"
      sha256 "4eb866ebddcf04b4dbf6afbb99982993122cc30fcfd386fe410ac3ed35d5157c"
    end
  end

  # No zap stanza required
end
