# This file was generated by GoReleaser. DO NOT EDIT.
cask "gelf" do
  desc "AI-powered Git commit message generator using Vertex AI (Gemini)"
  homepage "https://github.com/EkeMinusYou/gelf"
  version "0.0.24"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gelf"
  bash_completion "completions/gelf.bash"
  zsh_completion "completions/gelf.zsh"
  fish_completion "completions/gelf.fish"

  on_macos do
    on_intel do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.24/gelf_Darwin_x86_64.tar.gz"
      sha256 "a33a335284d58ac83871790e4958926de25e0311af272c7ba14ccb3c4ad32830"
    end
    on_arm do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.24/gelf_Darwin_arm64.tar.gz"
      sha256 "039d7fcfb26d5393839a6996eb98ba963766806350da366af843cea3b90c962a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.24/gelf_Linux_x86_64.tar.gz"
      sha256 "56e8a59769c6c27e94dc59ac3655c12603e7e3ab25c56968668ae4a51e0b24c8"
    end
    on_arm do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v0.0.24/gelf_Linux_arm64.tar.gz"
      sha256 "d4507606c53cff3afa8806a17065f930f3e1414b46fac52b372c6545d276721a"
    end
  end

  # No zap stanza required
end
