# This file was generated by GoReleaser. DO NOT EDIT.
cask "gelf" do
  name "gelf"
  desc "AI-powered Git commit message generator using Vertex AI (Gemini)"
  homepage "https://github.com/EkeMinusYou/gelf"
  version "0.0.34"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gelf"
  bash_completion "completions/gelf.bash"
  zsh_completion "completions/gelf.zsh"
  fish_completion "completions/gelf.fish"

  on_macos do
    on_intel do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v#{version}/gelf_Darwin_x86_64.tar.gz"
      sha256 "348e31afd462bb83c0dc1f3e397b66ced37a3b5213f6293160430b440865861a"
    end
    on_arm do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v#{version}/gelf_Darwin_arm64.tar.gz"
      sha256 "d7c0a2f56db3a0bf9ee6cd3239067fb20213ba0a8c717b9273ac7f18d6d2bac3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v#{version}/gelf_Linux_x86_64.tar.gz"
      sha256 "51f685c71f24b2d28ad6631cbd0d57c85bf7cde6f5069f21575f6d0a1adc6df4"
    end
    on_arm do
      url "https://github.com/EkeMinusYou/gelf/releases/download/v#{version}/gelf_Linux_arm64.tar.gz"
      sha256 "a76a76376e89b12bf9569b495158e8ca35cff30a8e54283be344355d6be2eacb"
    end
  end

  # No zap stanza required
end
